/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CustomButton {
        "color": string;
        "disabled": boolean;
        "size": 'small' | 'large';
    }
    interface CustomHeader {
        "items": string;
    }
    interface CustomList {
        "navs": string;
    }
}
declare global {
    interface HTMLCustomButtonElement extends Components.CustomButton, HTMLStencilElement {
    }
    var HTMLCustomButtonElement: {
        prototype: HTMLCustomButtonElement;
        new (): HTMLCustomButtonElement;
    };
    interface HTMLCustomHeaderElement extends Components.CustomHeader, HTMLStencilElement {
    }
    var HTMLCustomHeaderElement: {
        prototype: HTMLCustomHeaderElement;
        new (): HTMLCustomHeaderElement;
    };
    interface HTMLCustomListElement extends Components.CustomList, HTMLStencilElement {
    }
    var HTMLCustomListElement: {
        prototype: HTMLCustomListElement;
        new (): HTMLCustomListElement;
    };
    interface HTMLElementTagNameMap {
        "custom-button": HTMLCustomButtonElement;
        "custom-header": HTMLCustomHeaderElement;
        "custom-list": HTMLCustomListElement;
    }
}
declare namespace LocalJSX {
    interface CustomButton {
        "color"?: string;
        "disabled"?: boolean;
        "size"?: 'small' | 'large';
    }
    interface CustomHeader {
        "items"?: string;
    }
    interface CustomList {
        "navs"?: string;
    }
    interface IntrinsicElements {
        "custom-button": CustomButton;
        "custom-header": CustomHeader;
        "custom-list": CustomList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "custom-button": LocalJSX.CustomButton & JSXBase.HTMLAttributes<HTMLCustomButtonElement>;
            "custom-header": LocalJSX.CustomHeader & JSXBase.HTMLAttributes<HTMLCustomHeaderElement>;
            "custom-list": LocalJSX.CustomList & JSXBase.HTMLAttributes<HTMLCustomListElement>;
        }
    }
}
